#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  KeyTypeBench-20260603/Scripts/run_edge_variance.sh --model /path/to/model.gguf [options]

Runs the edge suite repeatedly in release mode, writes each run to a separate result directory,
and prints the observed range for benchmark metrics. It does not estimate variance: the summary is
created only from aggregate.json files generated by the requested runs.

Options:
  --model PATH              GGUF model to evaluate. Required.
  --runs N                  Number of runs. Defaults to 5; minimum 3.
  --result-name NAME        Parent directory under Results/. Defaults to edge-variance-<timestamp>.
  --profile PATH            ACPF profile path.
  --profile-directory DIR   Directory containing <family>.acpf.bin profiles.
  --context-length N        Llama context length.
  -h, --help                Show this help.
EOF
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bench_root="$(cd "$script_dir/.." && pwd)"
repo_root="$(cd "$bench_root/.." && pwd)"

model_path=""
runs=5
result_name=""
profile_path=""
profile_directory=""
context_length=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model) model_path="${2:-}"; shift 2 ;;
    --runs) runs="${2:-}"; shift 2 ;;
    --result-name) result_name="${2:-}"; shift 2 ;;
    --profile) profile_path="${2:-}"; shift 2 ;;
    --profile-directory) profile_directory="${2:-}"; shift 2 ;;
    --context-length) context_length="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

if [[ -z "$model_path" || ! -f "$model_path" ]]; then
  echo "--model must name an existing GGUF file." >&2
  exit 2
fi
if ! [[ "$runs" =~ ^[0-9]+$ ]] || (( runs < 3 )); then
  echo "--runs must be an integer of at least 3." >&2
  exit 2
fi

if [[ -z "$result_name" ]]; then
  result_name="edge-variance-$(date -u +%Y%m%dT%H%M%SZ)"
fi
result_root="$bench_root/Results/$result_name"
mkdir -p "$result_root"

common_args=(--suite edge --cases "$bench_root/Datasets/edge.jsonl" --model "$model_path")
[[ -n "$profile_path" ]] && common_args+=(--profile "$profile_path")
[[ -n "$profile_directory" ]] && common_args+=(--profile-directory "$profile_directory")
[[ -n "$context_length" ]] && common_args+=(--context-length "$context_length")

for run in $(seq 1 "$runs"); do
  output="$result_root/run-$run"
  echo "Running edge benchmark $run of $runs -> $output"
  (
    cd "$repo_root"
    swift run -c release --package-path Packages/KeyTypeBench KeyTypeBench run \
      "${common_args[@]}" --output "$output"
  ) 2>&1 | tee "$output.log"
done

python3 - "$result_root" <<'PY'
import json
import pathlib
import statistics
import sys

root = pathlib.Path(sys.argv[1])
metrics = ("precisionWhenShown", "wrongShowRate", "positiveCoverage", "qualityScore", "p50TotalMs", "p95TotalMs")
values = {metric: [] for metric in metrics}
for path in sorted(root.glob("run-*/aggregate.json")):
    aggregates = json.loads(path.read_text())
    if len(aggregates) != 1:
        raise SystemExit(f"Expected one aggregate in {path}, found {len(aggregates)}")
    for metric in metrics:
        values[metric].append(aggregates[0][metric])

if len(next(iter(values.values()))) < 3:
    raise SystemExit("Fewer than three aggregate files were produced; no variance summary written.")

summary = {
    "runCount": len(next(iter(values.values()))),
    "metrics": {
        metric: {
            "min": min(series),
            "max": max(series),
            "mean": statistics.fmean(series),
            "sampleStandardDeviation": statistics.stdev(series),
        }
        for metric, series in values.items()
    },
}
(root / "variance-summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
print(json.dumps(summary, indent=2, sort_keys=True))
PY

echo "Variance summary: $result_root/variance-summary.json"
